# Running Python

1. Execute a valid Python file

    ```bash
    $ python foo.py
    ```

1. Python Interpreter

    ```bash
    $ python
    ```

1. iPython (Interactive Python)

    ```bash
    $ ipython
    ```

1. Jupyter / iPython notebook (also recommended)

    ```
    $ jupyter notebook
    ```
    
    This is similar to iPython but browser based. It has some very cool features (i.e you can run specific segments of code). For development, some people may have a preference for the simpler command-line iPython. 


1. IDEs: PyCharm or Visual Studio Code

    You are on your own to figure this out. I hear they're nice once they're setup, but it's some up-front cost to configure it to work nicely with anaconda, matplotlib, etc. 
    

1. Text Editors: Sublime Text

    Free (in the same way WinRAR is free) text editor with nice default features and a lot of plugin options. Easier to configure to work with your Python3 installation, and can execute a .py file with a hotkey. If you don't have a worthwhile default text editor, I highly recommend it.



# Jupyter Notebook Cheat Sheet

### Running a cell
A cell is a block of code. Click the cell below and press the "play" button above or type Shift+Enter. The code will run, print output, and then advance to the next cell. Type Ctrl+Enter to run but not advance.

Hint: If you're getting an error that says a variable is undefined, make sure you've ran the cell that defines the variable before executing ones that will use it.

In [3]:
x = 10
x = 2*x
print(x)

20


### Running code in another file
Create a file in the same directory called ``hello.py`` with this line

```python
print ('hello world')
```

Now you can run it from jupyter:

In [4]:
%run hello.py

ERROR:root:File `'hello.py'` not found.


Basic Data Types
==============

Numerical and Logical Types
---

In [2]:
x = 1 #
print(x, type(x))
x = True
print(x, type(x))
x = 1.0
print(x, type(x))
x = 1e10
print(x, type(x))

1 <class 'int'>
True <class 'bool'>
1.0 <class 'float'>
10000000000.0 <class 'float'>


Strings
--

In [8]:
X="This is a string" #Set X to a string object defined using double quotes
print(X)

This is a string


In [17]:
Y='So is this!' #Set Y to a string object defined using single quotes
print(Y)

So is this!


In [18]:
Z = "If you use double quotes, it's okay to use single quotes inside, and vice versa. Otherwise, use an escape character \\. " + 'Also, there\'s no difference to strings defined with either one.'
print(Z)

If you use double quotes, it's okay to use single quotes inside, and vice versa. Otherwise, use an escape character \. Also, there's no difference to strings defined with either one.


In [19]:
print(X[0])

T


In [20]:
print(X[1:] )

his is a string
g


In [24]:
print(X.split())
print(X.split('i'))

['This', 'is', 'a', 'string']
['Th', 's ', 's a str', 'ng']


In [25]:
print(X + Y)
print(X + '.' + " " + Y)

This is a stringSo is this!
This is a string. So is this!


In [23]:
XYZ = "Notice strings are immutable in Python. So make them lists first, then edit, then back into strings."
XYZ[0] = "n"

TypeError: 'str' object does not support item assignment

Containers
========

Tuples
--

In [45]:
X = (1,"2","Fang",4.1,5)            #Define tuple
print(type(X))

<class 'tuple'>


In [31]:
print("X=", X)           #Print the tuple 

X= (1, '2', 'Fang', 4.1, 5)


In [33]:
print("X[2]=", X[2])     #Print the first element of the tuple

X[2]= Fang


In [36]:
print( X[4] )    #Print the last element of the tuple
print( X[-1] )   #Print the last element of the tuple

5
5


In [37]:
print(len(X)) #Pring length of tuple

5


In [46]:
X[0]=5                  #Set element of tuple ! ERROR (tuples are immutable)

TypeError: 'tuple' object does not support item assignment

Lists
--

Python lists are more like C-style linked lists than they are arrays. They are indexable, sliceable, comparable, addable, multiplyable (?), and more. 

In [39]:
X = [1,2,"Fang",4,5]         #Define list
print(type(X))           #Show type of X

<class 'list'>


In [40]:
print(X)       #Print the list

[1, 2, 'Fang', 4, 5]


In [41]:
print(X[2])     #Print the first element of the list

Fang


In [ ]:
print(X[4])
print(X[-1])    #Print the last element of the list

In [ ]:
print(len(X))

In [ ]:
X[0] = 5                  #Change the list. 
print(X)

In [ ]:
X.append(6)          # Append *one* item to list. Takes object as an argument.
print(X)

In [ ]:
X = [1, 2, 3, 4, 5, 6]
X.extend([7, 8]) # add elements 7, 8 to end of X. Takes list of objects as an argument.
print(X)

In [ ]:
Y = X + [7,8]   # concatenate and retern a *new* list
print(X)
print(Y)

In [58]:
X = [1, 2, 3, 4, 5]
Y=X*2           # concatenate two copies of X (think: X+X)
print(Y)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [59]:
print(Y[0:4]) # slice a list with start, stop

[1, 2, 3, 4]


In [60]:
print(Y[0:12:2]) #slice a list, adding an increment

[1, 3, 5, 2, 4]


In [55]:
print(X[:-1]) #slice a list, remove the last element

[1, 2]


In [66]:
X = [1,2,3]
Y = ['a','b','c']
Z = zip(X,Y) # Make one list out of two using tuples

for item in Z: # Ignore the for loop for now
    print(item)

(1, 'a')
(2, 'b')
(3, 'c')


### Create a plot using matplotlib

In [33]:
%matplotlib inline
import matplotlib.pyplot as plt
x = [1, 2, 3, 4]
y = [2, 30, 4, 20]
plt.plot(x, y)
plt.show()

KeyboardInterrupt: 

Dictionaries
--

A dictionary, also known as a hash table, provides constant time lookup through the use of keys. Both keys and values can be of any type, as long as they provide a __hash__ method. 

For instance, you wouldn't use a list as a key, because it is mutable (could change). If it changes, then you will have lost the key to the previously stored values. However, strings and tuples are immutable and thus don't suffer from this problem.

In [36]:
X = {"Bob": 192731, "Mary": 281927, "Joe": 103124} #Define a dictionary of key-value pairs
print("type(X)",type(X))

type(X) <class 'dict'>


In [37]:
print("X=", X)                    #Print the dictionary

X= {'Bob': 192731, 'Mary': 281927, 'Joe': 103124}


In [38]:
print('X["Joe"]=', X["Joe"])      #Print the value for Joe

X["Joe"]= 103124


In [39]:
print('len(X)', len(X))           #Print the number of items

len(X) 3


In [40]:
print('X.keys()=',X.keys())       #Print the list of keys

X.keys()= dict_keys(['Bob', 'Mary', 'Joe'])


In [34]:
X=5 #Set X to integer object equal to 5
print("1: X",X)

X=5.0 #Set X to float object equal to 5.0
print("2: X=",X)

X=True #Set X to boolean True
print("3: X=",X)

X=500000000000000000000000000000000000000000000000000000000000000 # Python 3 integers have arbitrary precision
print("4: X=",X)

1: X 5
2: X= 5.0
3: X= True
4: X= 500000000000000000000000000000000000000000000000000000000000000


In [ ]:
print('X.values()=',X.values())   #Print the list of values


In [ ]:
X["Joe"]=772345                   #Change an element
print("X=", X)

In [ ]:
X["Alice"]=111111                 #Add a new element
print("X=", X) 

In [42]:
print(X["Pedro"]) #Notice that if an key is not yet in the dictionary, a KeyError exception is raised

KeyError: 'Pedro'

In [47]:
X["Pedro"] = X.get("Pedro", 0) + 2048 #Fix it by using dict.get(key, default_value)
print(X["Pedro"])

# Look into collections.defaultdict if you run into the above assignment situation a lot

2048


In [52]:
X = [1,2,3]
Y = ['a','b','c']
Z = dict(zip(X,Y)) # Zip two lists and use them as the key, value pairs for a dictionary

print(Z.items())

dict_items([(1, 'a'), (2, 'b'), (3, 'c')])


# Sets

Python sets are like a C++ style bag. They only care about storing unique elements and have fast lookup times.

In [71]:
s = set()

s.add(2)
s.add("Pedro")

print(s)

s.remove(2)

print(s)

{2, 'Pedro'}
{'Pedro'}


Containers with Nesting and Mixed Elements
--

In [48]:
X = [1,"Foo",False,[1,2,3],(1,True)] #Lists can contain mixed types!
print("X=", X)                        #Print the list

X= [1, 'Foo', False, [1, 2, 3], (1, True)]


In [49]:
#How can we get the second item in the tuple at the end of the list?
print(X[-1][1])

True


In [67]:
#But notice that this comes with problems if you access an unsubscriptable object (e.g int, float)
print(X[0][1])

TypeError: 'int' object is not subscriptable

Assignment Dynamics
==

Python has a weak type system (duck typing), unlike C. So a single variable can be bound to objects of many types. Also, variables do not require an up-front type declaration. However, you can use type hints in function definitions for code organization and for use with third-party debuggers.

In [50]:
A = 5  #Assign the object "5" to the name A
B = A  #Assign the object that A refers to to the name B
print("A=",A,"B=",B )

A= 5 B= 5


In [51]:
B = 7               
print("A=",A,"B=",B)

A= 5 B= 7


In [52]:
A = [1,2,3,4,5]
B = A
print("A=",A,"B=",B )

A= [1, 2, 3, 4, 5] B= [1, 2, 3, 4, 5]


In [53]:
A = [1,2,3,4,5]
B = A
B = [5,4,3,2,1]        
print ("A=",A,"B=",B ) 

A= [1, 2, 3, 4, 5] B= [5, 4, 3, 2, 1]


In [54]:
A = [1,2,3,4,5]
B=A
A.append(6)
B.append(7)
print ("A=",A,"B=",B )

A= [1, 2, 3, 4, 5, 6, 7] B= [1, 2, 3, 4, 5, 6, 7]


In [ ]:
A = [1,2,3,4,5]
B = A
B[0]=-1
print ("A=",A,"B=",B)

Basic Control Flow
==


If-Elif-Else
--

In [55]:
#Basic If-Elif-Else
X=5
if(X<0):
    print("X is negative")
elif(X==0):
    print("X is zero")
else:
    print("X is positive")


X is positive


For and While
--

In [56]:
#Basic for loop using range()
A = [1, 2, 3, 4, 5]
for i in range(len(A)): 
    print(i, A[i])

0 1
1 2
2 3
3 4
4 5


In [74]:
#Basic for loop using iterable
names = ["alex", "john", "paul"]

for name in names:
    print(name)


alex
john
paul


In [77]:
# Notice the first variable is for your convenience 
# The second one is the list you are iterating over (in this case "names").
for this_variable_is_for_the_for_loop in names:
    print(this_variable_is_for_the_for_loop)

alex
john
paul


In [79]:
for this_variable_is_for_the_for_loop in names:
    print(this_variable_is_for_the_for_loop)
else: # The else section is only executed if the for loop terminates naturally, as seen above.
    print("Pedro")

alex
john
paul
Pedro


In [80]:
for this_variable_is_for_the_for_loop in names:
    print(this_variable_is_for_the_for_loop)
    break
else: # Here, the break prevents the else from executing naturally.
    print("Pedro")

alex


In [81]:
# A natural use is if you're searching for an element print something, else print not found.
for name in names:
    if name == "Pedro":
        break
else:
    print("Not found")

Not found


In [82]:
#Basic while loop
x=5    
while(x > 0):
    print(x)
    x-=1

5
4
3
2
1


In [84]:
# Python has no do-while loop; use this instead
x = 0
while True:
    print(x)
    x += 1
    if x > 5:
        break


0
1
2
3
4
5


In [87]:
# Here's a way to unpack a dictionary (or multiple lists)
d = dict(zip([1,2,3],[7,8,9]))

for key, value in d.items():
    print(f"d[{key}] = {value}")


d[1] = 7
d[2] = 8
d[3] = 9


# List Comprehensions

These are the "pythonic" way of creating lists. If at all possible, use these and benefit from Python's optimizations.

In [89]:
l = [0 for _ in range(20)]
print(l)

l = [(key, value) for key, value in d.items()]
print(l)

l = [number for number in range(0,20) if number % 2 == 0]
print(l)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[(1, 7), (2, 8), (3, 9)]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


Mathematical and Logical Operators
==

In [58]:
print ("2**4=", 2**4 )  # Computing Powers

2**4= 16


In [59]:
print ("2/4=", 2/4 )    # "True division" of int by int

# Note: the / operator for ints was "floor division" 
# in Python 2.x, so would give a result of 0 for this example

2/4= 0.5


In [60]:
print ("2//4=", 2//4 )  # "Floor division"

2//4= 0


In [61]:
print ("2/4.=", 2/4.)   # Division of int by float (True division)

2/4.= 0.5


In [62]:
print ("2./4=", 2./4)   # Division of float by int

2./4= 0.5


In [63]:
print ("True or False=", True or False) #Logical or

True or False= True


In [64]:
print ("True and False=", True and False) #Logical and

True and False= False


In [65]:
print ("not(False)=", not(False)) #Logical not

not(False)= True


Functions
==

In [66]:
def f(a):             #Define a basic function of 1-argument
    return a**2

print ("f(2)=",f(2))


f(2)= 4


In [67]:
def g(h,a,b):         #Define a function of 3-arguments where h is a function and a and b are numbers
    return h(a)+h(b)

print ("g(f,2,3)=",g(f,2,3))


g(f,2,3)= 13


In [ ]:
# Add type hints
def create_person(name: str, age: int, children: [str]) -> bool:
    return

NumPy Arrays
--

In [68]:
import numpy as np
X = np.array([[1,2],[3,4],[5,6]])
print ("X=\n",X)

X=
 [[1 2]
 [3 4]
 [5 6]]


In [69]:
print ("X.shape=", X.shape)

X.shape= (3, 2)


In [74]:
print ("X[0,1]=", X[0,1])

X[0,1]= 2


In [75]:
print ("X[0,:]=", X[0,:])

X[0,:]= [1 2]


In [76]:
Y = X[0,:]
print(Y.shape)

(2,)


In [77]:
print ("X[:,1]=", X[:,1])

X[:,1]= [2 4 6]


In [78]:
print ("2*X=\n", 2*X)

2*X=
 [[ 2  4]
 [ 6  8]
 [10 12]]


In [79]:
print ("3: 5+X=\n", 5+X)


3: 5+X=
 [[ 6  7]
 [ 8  9]
 [10 11]]


In [80]:
Y = np.array([[-1,1,-1]])
print ("Y=\n",Y)

Y=
 [[-1  1 -1]]


In [81]:
print ("6: Y.T=\n", Y.T)

6: Y.T=
 [[-1]
 [ 1]
 [-1]]


In [84]:
print ("X, Y, Y.dot(X)=\n", X, Y, Y.dot(X))

X, Y, Y.dot(X)=
 [[1 2]
 [3 4]
 [5 6]] [[-1  1 -1]] [[-3 -4]]


In [85]:
print ("np.dot(Y, X)=\n", np.dot(Y, X))

np.dot(Y, X)=
 [[-3 -4]]


In [86]:
print ("Y.T + X =\n", Y.T + X)

Y.T + X =
 [[0 1]
 [4 5]
 [4 5]]
